-- Create the Triggers used to assign new unique keys to various primary key columns
-- $Id: createSequenceTriggers.sql 888 2007-03-01 16:27:31Z drmills $

CREATE OR REPLACE
TRIGGER ASSIGN_USER_ID BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
 IF :NEW.USER_ID IS NULL OR :NEW.USER_ID < 0 THEN
   SELECT USER_SEQ.NEXTVAL
     INTO :NEW.USER_ID
     FROM DUAL;
   END IF;
END;
/

CREATE OR REPLACE
TRIGGER ASSIGN_COURSE_ID BEFORE INSERT ON COURSES
FOR EACH ROW
BEGIN
 IF :NEW.COURSE_ID IS NULL OR :NEW.COURSE_ID < 0 THEN
   SELECT COURSE_SEQ.NEXTVAL
     INTO :NEW.COURSE_ID
     FROM DUAL;
   END IF;
END;
/

CREATE OR REPLACE
TRIGGER ASSIGN_ASSIGNMENT_ID BEFORE INSERT ON ASSIGNMENTS
FOR EACH ROW
BEGIN
 IF :NEW.ASG_ID IS NULL OR :NEW.ASG_ID < 0 THEN
   SELECT ASSIGNMENT_SEQ.NEXTVAL
     INTO :NEW.ASG_ID
     FROM DUAL;
   END IF;
END;
/
