-- $Id: creates3SchemaObjects.sql 

--DROP TABLE USERS;
CREATE TABLE USERS
(
USER_ID NUMBER(15) NOT NULL,
FIRST_NAME VARCHAR2(30),
LAST_NAME VARCHAR2(30),
LOGIN_NAME VARCHAR2(30),
PASSWORD VARCHAR2(30),
EMAIL VARCHAR2(25) NOT NULL,
TYPE NUMBER NOT NULL,
MOBILE VARCHAR2(20),
IS_ACTIVE NUMBER(1),
CREATED_DATE DATE NOT NULL,
MODIFIED_DATE DATE NOT NULL,
DATE_OF_BIRTH DATE NOT NULL
)
;

CREATE TABLE COURSES
(
COURSE_ID NUMBER(15) NOT NULL,
NAME VARCHAR2(40) NOT NULL,
DESCRIPTION VARCHAR2(200),
IS_ACTIVE NUMBER(1),
CREATED_DATE DATE NOT NULL,
MODIFIED_DATE DATE NOT NULL
)
;

CREATE TABLE ASSIGNMENTS
(
ASG_ID NUMBER NOT NULL,
NAME NUMBER(15) NOT NULL,
DESCRIPTION VARCHAR2(400),
COURSE_ID NUMBER(15) NOT NULL,
CREATED_DATE DATE NOT NULL,
MODIFIED_DATE DATE NOT NULL,
IS_ACTIVE NUMBER(1)
)
;

CREATE TABLE STD_CRS_ASG
(
STUDENT_ID NUMBER(15) NOT NULL,
COURSE_ID NUMBER(15) NOT NULL,
ASG_ID NUMBER NOT NULL,
SUPER_ID NUMBER(15) NOT NULL,
STATUS VARCHAR2(30),
FILE_PATH VARCHAR(900) NOT NULL,
CREATED_DATE DATE NOT NULL,
MODIFIED_DATE DATE NOT NULL,
IS_ACTIVE NUMBER(1),
NOTES VARCHAR(900) NOT NULL
)
;

CREATE TABLE ENROLLMENTS
(
IS_ACTIVE NUMBER(1),
STUDENT_ID NUMBER(15) NOT NULL,
SUPER_ID NUMBER(15) NOT NULL,
COURSE_ID NUMBER(15) NOT NULL,
STATUS VARCHAR2(30),
CREATED_DATE DATE NOT NULL,
MODIFIED_DATE DATE NOT NULL
)
;

CREATE TABLE COMMENTS
(
STUDENT_ID NUMBER(15) NOT NULL,
SUPER_ID NUMBER(15) NOT NULL,
COURSE_ID NUMBER(15) NOT NULL,
ASG_ID NUMBER NOT NULL,
TEXT VARCHAR2(900) NOT NULL,
CREATED_DATE DATE NOT NULL,
MODIFIED_DATE DATE NOT NULL,
IS_ACTIVE NUMBER(1)
)
;

CREATE TABLE SUP_CRS
(
SUPER_ID NUMBER(15) NOT NULL,
COURSE_ID NUMBER(15) NOT NULL,
CREATED_DATE DATE NOT NULL,
MODIFIED_DATE DATE NOT NULL,
IS_ACTIVE NUMBER(1)
)
;

ALTER TABLE USERS
ADD CONSTRAINT USERS_PK PRIMARY KEY
(
USER_ID
)
 ENABLE
;

ALTER TABLE COURSES
ADD CONSTRAINT COURSES_PK PRIMARY KEY
(
COURSE_ID
)
 ENABLE
;

ALTER TABLE ASSIGNMENTS
ADD CONSTRAINT ASSIGNMENTS_PK PRIMARY KEY
(
ASG_ID
)
 ENABLE
;


ALTER TABLE STD_CRS_ASG
ADD CONSTRAINT STD_CRS_ASG_PK PRIMARY KEY
(
STUDENT_ID,
COURSE_ID,
ASG_ID,
SUPER_ID
)
 ENABLE
;

ALTER TABLE ENROLLMENTS
ADD CONSTRAINT ENROLLMENTS_PK PRIMARY KEY
(
STUDENT_ID,
COURSE_ID,
SUPER_ID
)
 ENABLE
;

ALTER TABLE COMMENTS
ADD CONSTRAINT COMMENTS_PK PRIMARY KEY
(
STUDENT_ID,
COURSE_ID,
ASG_ID,
SUPER_ID
)
 ENABLE
;

ALTER TABLE SUP_CRS
ADD CONSTRAINT SUP_CRS_PK PRIMARY KEY
(
SUPER_ID,
COURSE_ID
)
 ENABLE
;


ALTER TABLE USERS
ADD CONSTRAINT USERS_LOGIN_NAME_UNIQUE UNIQUE
(
LOGIN_NAME
)
 ENABLE
;

ALTER TABLE ASSIGNMENTS
ADD CONSTRAINT ASSIGNMENTS_COURSES_FK FOREIGN KEY
(
COURSE_ID
)
REFERENCES COURSES
(
COURSE_ID
) ENABLE
;

ALTER TABLE STD_CRS_ASG
ADD CONSTRAINT STD_CRS_ASG_STUDENT_FK FOREIGN KEY
(
STUDENT_ID
)
REFERENCES USERS
(
USER_ID
) ENABLE
;

ALTER TABLE STD_CRS_ASG
ADD CONSTRAINT STD_CRS_ASG_SUPERVISOR_FK FOREIGN KEY
(
SUPER_ID
)
REFERENCES USERS
(
USER_ID
) ENABLE
;

ALTER TABLE STD_CRS_ASG
ADD CONSTRAINT STD_CRS_ASG_COURSES_FK FOREIGN KEY
(
COURSE_ID
)
REFERENCES COURSES
(
COURSE_ID
) ENABLE
;

ALTER TABLE STD_CRS_ASG
ADD CONSTRAINT STD_CRS_ASG_ASSGINMENTS_FK FOREIGN KEY
(
ASG_ID
)
REFERENCES ASSIGNMENTS
(
ASG_ID
) ENABLE
;


ALTER TABLE ENROLLMENTS
ADD CONSTRAINT ENROLLMENTS_STUDENT_FK FOREIGN KEY
(
STUDENT_ID
)
REFERENCES USERS
(
USER_ID
) ENABLE
;

ALTER TABLE ENROLLMENTS
ADD CONSTRAINT ENROLLMENTS_SUPERVISOR_FK FOREIGN KEY
(
SUPER_ID
)
REFERENCES USERS
(
USER_ID
) ENABLE
;

ALTER TABLE ENROLLMENTS
ADD CONSTRAINT ENROLLMENTS_COURSES_FK FOREIGN KEY
(
COURSE_ID
)
REFERENCES COURSES
(
COURSE_ID
) ENABLE
;



ALTER TABLE COMMENTS
ADD CONSTRAINT COMMENTS_STUDENT_FK FOREIGN KEY
(
STUDENT_ID
)
REFERENCES USERS
(
USER_ID
) ENABLE
;

ALTER TABLE COMMENTS
ADD CONSTRAINT COMMENTS_SUPERVISOR_FK FOREIGN KEY
(
SUPER_ID
)
REFERENCES USERS
(
USER_ID
) ENABLE
;

ALTER TABLE COMMENTS
ADD CONSTRAINT COMMENTS_COURSES_FK FOREIGN KEY
(
COURSE_ID
)
REFERENCES COURSES
(
COURSE_ID
) ENABLE
;

ALTER TABLE COMMENTS
ADD CONSTRAINT COMMENTS_ASSGINMENTS_FK FOREIGN KEY
(
ASG_ID
)
REFERENCES ASSIGNMENTS
(
ASG_ID
) ENABLE
;


ALTER TABLE SUP_CRS
ADD CONSTRAINT SUP_CRS_SUPERVISOR_FK FOREIGN KEY
(
SUPER_ID
)
REFERENCES USERS
(
USER_ID
) ENABLE
;

ALTER TABLE SUP_CRS
ADD CONSTRAINT SUP_CRS_COURSES_FK FOREIGN KEY
(
COURSE_ID
)
REFERENCES COURSES
(
COURSE_ID
) ENABLE
;


ALTER TABLE USERS
ADD CONSTRAINT USERS_CHK CHECK
(IS_ACTIVE in (0,1))
 ENABLE
;

ALTER TABLE COURSES
ADD CONSTRAINT COURSES_CHK CHECK
(IS_ACTIVE in (0,1))
 ENABLE
;

ALTER TABLE ASSIGNMENTS
ADD CONSTRAINT ASSIGNMENTS_CHK CHECK
(IS_ACTIVE in (0,1))
 ENABLE
;

ALTER TABLE STD_CRS_ASG
ADD CONSTRAINT STD_CRS_ASG_CHK CHECK
(IS_ACTIVE in (0,1))
 ENABLE
;

ALTER TABLE ENROLLMENTS
ADD CONSTRAINT ENROLLMENTS_CHK CHECK
(IS_ACTIVE in (0,1))
 ENABLE
;

ALTER TABLE COMMENTS
ADD CONSTRAINT COMMENTS_CHK CHECK
(IS_ACTIVE in (0,1))
 ENABLE
;

ALTER TABLE SUP_CRS
ADD CONSTRAINT SUP_CRS_CHK CHECK
(IS_ACTIVE in (0,1))
 ENABLE
;

CREATE SEQUENCE USER_SEQ INCREMENT BY 1 START WITH 300 CACHE 10 ;

CREATE SEQUENCE COURSE_SEQ INCREMENT BY 1 START WITH 300;

CREATE SEQUENCE ASSIGNMENT_SEQ INCREMENT BY 1 START WITH 300;


CREATE TABLE HISTORY_USERS
(
USER_ID NUMBER(15) NOT NULL,
FIRST_NAME VARCHAR2(30),
LAST_NAME VARCHAR2(30),
LOGIN_NAME VARCHAR2(30),
PASSWORD VARCHAR2(30),
EMAIL VARCHAR2(25) NOT NULL,
TYPE NUMBER NOT NULL,
MOBILE VARCHAR2(20),
IS_ACTIVE NUMBER(1),
CREATED_DATE DATE NOT NULL,
MODIFIED_DATE DATE NOT NULL,
DATE_OF_BIRTH DATE NOT NULL
)
;

CREATE TABLE HISTORY_COURSES
(
COURSE_ID NUMBER(15) NOT NULL,
NAME VARCHAR2(40) NOT NULL,
DESCRIPTION VARCHAR2(200),
IS_ACTIVE NUMBER(1),
CREATED_DATE DATE NOT NULL,
MODIFIED_DATE DATE NOT NULL
)
;

CREATE TABLE HISTORY_ASSIGNMENTS
(
ASG_ID NUMBER NOT NULL,
NAME NUMBER(15) NOT NULL,
DESCRIPTION VARCHAR2(400),
COURSE_ID NUMBER(15) NOT NULL,
CREATED_DATE DATE NOT NULL,
MODIFIED_DATE DATE NOT NULL,
IS_ACTIVE NUMBER(1)
)
;

CREATE TABLE HISTORY_STD_CRS_ASG
(
STUDENT_ID NUMBER(15) NOT NULL,
COURSE_ID NUMBER(15) NOT NULL,
ASG_ID NUMBER NOT NULL,
SUPER_ID NUMBER(15) NOT NULL,
STATUS VARCHAR2(30),
FILE_PATH VARCHAR(900) NOT NULL,
CREATED_DATE DATE NOT NULL,
MODIFIED_DATE DATE NOT NULL,
IS_ACTIVE NUMBER(1),
NOTES VARCHAR(900) NOT NULL
)
;

CREATE TABLE HISTORY_ENROLLMENTS
(
IS_ACTIVE NUMBER(1),
STUDENT_ID NUMBER(15) NOT NULL,
SUPER_ID NUMBER(15) NOT NULL,
COURSE_ID NUMBER(15) NOT NULL,
STATUS VARCHAR2(30),
CREATED_DATE DATE NOT NULL,
MODIFIED_DATE DATE NOT NULL
)
;

CREATE TABLE HISTORY_COMMENTS
(
STUDENT_ID NUMBER(15) NOT NULL,
SUPER_ID NUMBER(15) NOT NULL,
COURSE_ID NUMBER(15) NOT NULL,
ASG_ID NUMBER NOT NULL,
TEXT VARCHAR2(900) NOT NULL,
CREATED_DATE DATE NOT NULL,
MODIFIED_DATE DATE NOT NULL,
IS_ACTIVE NUMBER(1)
)
;

CREATE TABLE HISTORY_SUP_CRS
(
SUPER_ID NUMBER(15) NOT NULL,
COURSE_ID NUMBER(15) NOT NULL,
CREATED_DATE DATE NOT NULL,
MODIFIED_DATE DATE NOT NULL,
IS_ACTIVE NUMBER(1)
)
;


show error